package gui;

import dao.CargosDAO;
import dao.ClientesDAO;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import javax.swing.*;
import jdbc.MySQLConnection;

public class TelaAreaDeTrabalho extends javax.swing.JFrame {

    private final Connection conn;
    private boolean trocarUsuario = false;
    private boolean isMaximized = false;

    public void janelaCliente() {
        ClientesDAO clientesDao = new ClientesDAO(conn);
        TelaFormularioClientes tfc = new TelaFormularioClientes(clientesDao);
        tfc.setVisible(true);
    }
    
    public void janelaCargos() {
        CargosDAO cargosDao = new CargosDAO(conn);
        TelaFormularioCargos tfc = new TelaFormularioCargos(cargosDao);
        tfc.setVisible(true);
    }
    
    public void janelaEstoque() {
        TelaFormularioEstoque tle = new TelaFormularioEstoque(conn);
        tle.setVisible(true);
    }
    
    public void janelaFornecedor() {
        TelaFormularioFornecedores tff = new TelaFormularioFornecedores(conn);
        tff.setVisible(true);
    }
    
    public void janelaFuncionario() {
        TelaFormularioFuncionarios tff = new TelaFormularioFuncionarios(conn);
        tff.setVisible(true);
    }
    
    public void janelaPecas() {
        TelaFormularioPecas tfp = new TelaFormularioPecas(conn);
        tfp.setVisible(true);
    }
    
    public void janelaPedido() {
        TelaFormularioPedidos tfpd = new TelaFormularioPedidos(conn);
        tfpd.setVisible(true);
    }    
    
    public void janelaOS() {
        TelaFormularioOS tfos = new TelaFormularioOS(conn);
        tfos.setVisible(true);
    }
    
    public void janelaTrocaUsuario() {
        int opcao = JOptionPane.showConfirmDialog(null,
                "Você deseja trocar de usuário?", "Aviso",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (opcao == JOptionPane.YES_OPTION) {
            trocarUsuario = true;
            this.dispose();
            TelaLogin tl = new TelaLogin(conn);
            tl.setVisible(true);
        }
    }

    /**
     * Creates new form TelaAreaDeTrabalho
     */
    public TelaAreaDeTrabalho(Connection conn) {
        initComponents();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.conn = conn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/imgFundo/mecanica.jpg"));
        Image image = icon.getImage();
        painelDesktop = new javax.swing.JDesktopPane() {
            public void paintComponent(Graphics g) {
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }
        };
        btnCliente = new javax.swing.JButton();
        btnFuncionario = new javax.swing.JButton();
        btnFornecedor = new javax.swing.JButton();
        btnPecas = new javax.swing.JButton();
        btnPedido = new javax.swing.JButton();
        btnCargos = new javax.swing.JButton();
        btnEstoque = new javax.swing.JButton();
        btnOS = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnTrocarUsuario = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemFormClientes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemFormFuncionarios = new javax.swing.JMenuItem();
        menuItemFormCargos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuItemFormFornecedores = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        menuItemFormEstoque = new javax.swing.JMenuItem();
        menuItemFormPecas2 = new javax.swing.JMenuItem();
        menuItemFormPecas = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuItemFormPedidos = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuItemFormOrdemServico = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuItemTrocarUsuario = new javax.swing.JMenuItem();
        menuItemSairSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Area de Trabalho");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(900, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        painelDesktop.setBackground(new java.awt.Color(242, 242, 242));
        painelDesktop.setPreferredSize(new java.awt.Dimension(800, 600));

        btnCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCliente.setForeground(new java.awt.Color(204, 204, 255));
        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clientes.png"))); // NOI18N
        btnCliente.setText("Clientes");
        btnCliente.setMaximumSize(new java.awt.Dimension(135, 71));
        btnCliente.setMinimumSize(new java.awt.Dimension(135, 71));
        btnCliente.setPreferredSize(new java.awt.Dimension(135, 71));
        btnCliente.setHorizontalTextPosition(SwingConstants.CENTER);
        btnCliente.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCliente.setBorderPainted(false);
        btnCliente.setContentAreaFilled(false);
        btnCliente.setFocusPainted(false);
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        btnFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFuncionario.setForeground(new java.awt.Color(204, 204, 255));
        btnFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/funcionarios.png"))); // NOI18N
        btnFuncionario.setText("Funcionários");
        btnFuncionario.setMaximumSize(new java.awt.Dimension(135, 71));
        btnFuncionario.setMinimumSize(new java.awt.Dimension(135, 71));
        btnFuncionario.setPreferredSize(new java.awt.Dimension(135, 71));
        btnFuncionario.setHorizontalTextPosition(SwingConstants.CENTER);
        btnFuncionario.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFuncionario.setBorderPainted(false);
        btnFuncionario.setContentAreaFilled(false);
        btnFuncionario.setFocusPainted(false);
        btnFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionarioActionPerformed(evt);
            }
        });

        btnFornecedor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFornecedor.setForeground(new java.awt.Color(204, 204, 255));
        btnFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fornecedores.png"))); // NOI18N
        btnFornecedor.setText("Fornecedores");
        btnFornecedor.setMaximumSize(new java.awt.Dimension(135, 71));
        btnFornecedor.setMinimumSize(new java.awt.Dimension(135, 71));
        btnFornecedor.setPreferredSize(new java.awt.Dimension(135, 71));
        btnFornecedor.setHorizontalTextPosition(SwingConstants.CENTER);
        btnFornecedor.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFornecedor.setBorderPainted(false);
        btnFornecedor.setContentAreaFilled(false);
        btnFornecedor.setFocusPainted(false);
        btnFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorActionPerformed(evt);
            }
        });

        btnPecas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPecas.setForeground(new java.awt.Color(204, 204, 255));
        btnPecas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pecas.png"))); // NOI18N
        btnPecas.setText("Peças");
        btnPecas.setMaximumSize(new java.awt.Dimension(135, 71));
        btnPecas.setMinimumSize(new java.awt.Dimension(135, 71));
        btnPecas.setPreferredSize(new java.awt.Dimension(135, 71));
        btnPecas.setHorizontalTextPosition(SwingConstants.CENTER);
        btnPecas.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnPecas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPecas.setBorderPainted(false);
        btnPecas.setContentAreaFilled(false);
        btnPecas.setFocusPainted(false);
        btnPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPecasActionPerformed(evt);
            }
        });

        btnPedido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPedido.setForeground(new java.awt.Color(204, 204, 255));
        btnPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pedido.png"))); // NOI18N
        btnPedido.setText("Pedido");
        btnPedido.setHorizontalTextPosition(SwingConstants.CENTER);
        btnPedido.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPedido.setBorderPainted(false);
        btnPedido.setContentAreaFilled(false);
        btnPedido.setFocusPainted(false);
        btnPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoActionPerformed(evt);
            }
        });

        btnCargos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCargos.setForeground(new java.awt.Color(204, 204, 255));
        btnCargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cargos.png"))); // NOI18N
        btnCargos.setText("Cargos");
        btnCargos.setHorizontalTextPosition(SwingConstants.CENTER);
        btnCargos.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnCargos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCargos.setBorderPainted(false);
        btnCargos.setContentAreaFilled(false);
        btnCargos.setFocusPainted(false);
        btnCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargosActionPerformed(evt);
            }
        });

        btnEstoque.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEstoque.setForeground(new java.awt.Color(204, 204, 255));
        btnEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/estoque.png"))); // NOI18N
        btnEstoque.setText("Estoque");
        btnEstoque.setMaximumSize(new java.awt.Dimension(135, 71));
        btnEstoque.setMinimumSize(new java.awt.Dimension(135, 71));
        btnEstoque.setPreferredSize(new java.awt.Dimension(135, 71));
        btnEstoque.setHorizontalTextPosition(SwingConstants.CENTER);
        btnEstoque.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstoque.setBorderPainted(false);
        btnEstoque.setContentAreaFilled(false);
        btnEstoque.setFocusPainted(false);
        btnEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstoqueActionPerformed(evt);
            }
        });

        btnOS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnOS.setForeground(new java.awt.Color(204, 204, 255));
        btnOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ordem-de-servico.png"))); // NOI18N
        btnOS.setText("Ordem de Serviço");
        btnOS.setMaximumSize(new java.awt.Dimension(135, 71));
        btnOS.setMinimumSize(new java.awt.Dimension(135, 71));
        btnOS.setPreferredSize(new java.awt.Dimension(135, 71));
        btnOS.setHorizontalTextPosition(SwingConstants.CENTER);
        btnOS.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOS.setBorderPainted(false);
        btnOS.setContentAreaFilled(false);
        btnOS.setFocusPainted(false);
        btnOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOSActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 102, 102));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setMaximumSize(new java.awt.Dimension(135, 71));
        btnSair.setMinimumSize(new java.awt.Dimension(135, 71));
        btnSair.setPreferredSize(new java.awt.Dimension(135, 71));
        btnSair.setHorizontalTextPosition(SwingConstants.CENTER);
        btnSair.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.setBorderPainted(false);
        btnSair.setContentAreaFilled(false);
        btnSair.setFocusPainted(false);

        btnTrocarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTrocarUsuario.setForeground(new java.awt.Color(255, 102, 102));
        btnTrocarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/troca-user.png"))); // NOI18N
        btnTrocarUsuario.setText("Trocar Usuário");
        btnTrocarUsuario.setMaximumSize(new java.awt.Dimension(135, 71));
        btnTrocarUsuario.setMinimumSize(new java.awt.Dimension(135, 71));
        btnTrocarUsuario.setPreferredSize(new java.awt.Dimension(135, 71));
        btnTrocarUsuario.setHorizontalTextPosition(SwingConstants.CENTER);
        btnTrocarUsuario.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnTrocarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrocarUsuario.setBorderPainted(false);
        btnTrocarUsuario.setContentAreaFilled(false);
        btnTrocarUsuario.setFocusPainted(false);
        btnTrocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrocarUsuarioActionPerformed(evt);
            }
        });

        painelDesktop.setLayer(btnCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDesktop.setLayer(btnFuncionario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDesktop.setLayer(btnFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDesktop.setLayer(btnPecas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDesktop.setLayer(btnPedido, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDesktop.setLayer(btnCargos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDesktop.setLayer(btnEstoque, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDesktop.setLayer(btnOS, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDesktop.setLayer(btnSair, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDesktop.setLayer(btnTrocarUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelDesktopLayout = new javax.swing.GroupLayout(painelDesktop);
        painelDesktop.setLayout(painelDesktopLayout);
        painelDesktopLayout.setHorizontalGroup(
            painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDesktopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPecas, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOS, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelDesktopLayout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addComponent(btnTrocarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );
        painelDesktopLayout.setVerticalGroup(
            painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDesktopLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPecas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOS, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrocarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jMenu1.setText("Clientes");

        menuItemFormClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemFormClientes.setText("Formulário de Clientes");
        menuItemFormClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFormClientesActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemFormClientes);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Funcionários");

        menuItemFormFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemFormFuncionarios.setText("Formulário de Funcionários");
        menuItemFormFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFormFuncionariosActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemFormFuncionarios);

        menuItemFormCargos.setText("Formulário de Cargos");
        menuItemFormCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFormCargosActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemFormCargos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Fornecedores");

        menuItemFormFornecedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemFormFornecedores.setText("Formulário de Fornecedores");
        menuItemFormFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFormFornecedoresActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemFormFornecedores);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Peças");

        jMenu8.setText("Minhas Peças");

        menuItemFormEstoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemFormEstoque.setText("Controle de Estoque");
        menuItemFormEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFormEstoqueActionPerformed(evt);
            }
        });
        jMenu8.add(menuItemFormEstoque);

        menuItemFormPecas2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemFormPecas2.setText("Consulta de Peças");
        menuItemFormPecas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFormPecas2ActionPerformed(evt);
            }
        });
        jMenu8.add(menuItemFormPecas2);

        menuItemFormPecas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemFormPecas.setText("Formulário de Peças");
        menuItemFormPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFormPecasActionPerformed(evt);
            }
        });
        jMenu8.add(menuItemFormPecas);

        jMenu4.add(jMenu8);

        jMenuBar1.add(jMenu4);

        jMenu7.setText("Pedidos");

        menuItemFormPedidos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemFormPedidos.setText("Formulário de Pedidos");
        menuItemFormPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFormPedidosActionPerformed(evt);
            }
        });
        jMenu7.add(menuItemFormPedidos);

        jMenuBar1.add(jMenu7);

        jMenu5.setText("Ordem de Serviço");

        menuItemFormOrdemServico.setText("Formulário de OS");
        menuItemFormOrdemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFormOrdemServicoActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemFormOrdemServico);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Sair");

        menuItemTrocarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemTrocarUsuario.setText("Trocar de Usuário");
        menuItemTrocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTrocarUsuarioActionPerformed(evt);
            }
        });
        jMenu6.add(menuItemTrocarUsuario);

        menuItemSairSistema.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemSairSistema.setText("Sair do Sistema");
        menuItemSairSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairSistemaActionPerformed(evt);
            }
        });
        jMenu6.add(menuItemSairSistema);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemFormClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFormClientesActionPerformed
        // abre o formulário de clientes na tela
        janelaCliente();
    }//GEN-LAST:event_menuItemFormClientesActionPerformed

    private void menuItemFormFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFormFuncionariosActionPerformed
        // abre o formulário de funcionários na tela
        janelaFuncionario();
    }//GEN-LAST:event_menuItemFormFuncionariosActionPerformed

    private void menuItemFormFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFormFornecedoresActionPerformed
        // abre o formulário de fornecedores na tela
        janelaFornecedor();
    }//GEN-LAST:event_menuItemFormFornecedoresActionPerformed

    private void menuItemFormCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFormCargosActionPerformed
        // abre o formulário de cargos na tela
        janelaCargos();
    }//GEN-LAST:event_menuItemFormCargosActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // maximiza a janela
        if (!isMaximized) {
            this.setExtendedState(MAXIMIZED_BOTH);
            isMaximized = true;
        }
    }//GEN-LAST:event_formWindowActivated

    private void menuItemTrocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTrocarUsuarioActionPerformed
        // solicita confirmação para trocar de usuário        
        janelaTrocaUsuario();
    }//GEN-LAST:event_menuItemTrocarUsuarioActionPerformed

    private void menuItemSairSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairSistemaActionPerformed
        // solicita confirmação para sair do sistema
        int opcao = JOptionPane.showConfirmDialog(null,
                "Sair do sistema?", "Aviso",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (opcao == JOptionPane.YES_OPTION) {
            this.dispose();
            MySQLConnection.closeConnection();
        }
    }//GEN-LAST:event_menuItemSairSistemaActionPerformed

    private void menuItemFormPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFormPecasActionPerformed
        // abre o formulário de Peças na tela
        janelaPecas();
    }//GEN-LAST:event_menuItemFormPecasActionPerformed

    private void menuItemFormPecas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFormPecas2ActionPerformed
        // abre o formulário de Peças na tela, na aba de consulta de Peças
        TelaFormularioPecas tfpConsulta = new TelaFormularioPecas(conn);
        tfpConsulta.painelGuias.setSelectedIndex(1);
        tfpConsulta.setVisible(true);
    }//GEN-LAST:event_menuItemFormPecas2ActionPerformed

    private void menuItemFormEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFormEstoqueActionPerformed
        // abre o formulário de estoque na tela
        janelaEstoque();
    }//GEN-LAST:event_menuItemFormEstoqueActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int opcao = JOptionPane.showConfirmDialog(null,
                "Ao fechar a área de trabalho você será desconectado."
                + " Tem certeza que quer sair?", "Aviso",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (opcao == JOptionPane.YES_OPTION) {
            this.dispose();
            MySQLConnection.closeConnection();
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (!trocarUsuario) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        janelaCliente();
    }//GEN-LAST:event_btnClienteActionPerformed

    private void menuItemFormPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFormPedidosActionPerformed
        janelaPedido();
    }//GEN-LAST:event_menuItemFormPedidosActionPerformed

    private void btnFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionarioActionPerformed
        janelaFuncionario();
    }//GEN-LAST:event_btnFuncionarioActionPerformed

    private void btnFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorActionPerformed
        janelaFornecedor();
    }//GEN-LAST:event_btnFornecedorActionPerformed

    private void btnPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoActionPerformed
        janelaPedido();
    }//GEN-LAST:event_btnPedidoActionPerformed

    private void btnPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPecasActionPerformed
        janelaPecas();
    }//GEN-LAST:event_btnPecasActionPerformed

    private void btnCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargosActionPerformed
        janelaCargos();
    }//GEN-LAST:event_btnCargosActionPerformed

    private void btnEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueActionPerformed
        janelaEstoque();
    }//GEN-LAST:event_btnEstoqueActionPerformed

    private void btnTrocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrocarUsuarioActionPerformed
        janelaTrocaUsuario();
    }//GEN-LAST:event_btnTrocarUsuarioActionPerformed

    private void menuItemFormOrdemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFormOrdemServicoActionPerformed
        janelaOS();
    }//GEN-LAST:event_menuItemFormOrdemServicoActionPerformed

    private void btnOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOSActionPerformed
        janelaOS();
    }//GEN-LAST:event_btnOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAreaDeTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                Connection conn = MySQLConnection.getConnection();
                new TelaAreaDeTrabalho(conn).setVisible(true);
            } catch (Exception e) {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargos;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnEstoque;
    private javax.swing.JButton btnFornecedor;
    private javax.swing.JButton btnFuncionario;
    private javax.swing.JButton btnOS;
    private javax.swing.JButton btnPecas;
    private javax.swing.JButton btnPedido;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnTrocarUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuItemFormCargos;
    private javax.swing.JMenuItem menuItemFormClientes;
    private javax.swing.JMenuItem menuItemFormEstoque;
    private javax.swing.JMenuItem menuItemFormFornecedores;
    private javax.swing.JMenuItem menuItemFormFuncionarios;
    private javax.swing.JMenuItem menuItemFormOrdemServico;
    private javax.swing.JMenuItem menuItemFormPecas;
    private javax.swing.JMenuItem menuItemFormPecas2;
    private javax.swing.JMenuItem menuItemFormPedidos;
    private javax.swing.JMenuItem menuItemSairSistema;
    private javax.swing.JMenuItem menuItemTrocarUsuario;
    private javax.swing.JDesktopPane painelDesktop;
    // End of variables declaration//GEN-END:variables
}
