package gui;

import dao.PecasDAO;
import dao.PecasPedidosDAO;
import dao.PedidosDAO;
import java.awt.Component;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import jdbc.MySQLConnection;
import model.PecasPedidos;
import model.Pedidos;
import utilidades.LimpaComponente;

public class TelaFormularioPedidosFeitos extends javax.swing.JFrame {

    private final PedidosDAO pedidosDao;
    private final PecasPedidosDAO pecasPedidosDao;
    private final PecasDAO pecasDao;
    private final LimpaComponente limpar = new LimpaComponente();

    public void listarPedidosPendentes() {
        List<Pedidos> listaPendente = pedidosDao.listarPendentes();
        DefaultTableModel dadosPendentes = (DefaultTableModel) tabelaPendentes.getModel();
        dadosPendentes.setNumRows(0);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        for (Pedidos p : listaPendente) {
            if (p.getStatus().equals(Pedidos.Status.PENDENTE)) {
                dadosPendentes.addRow(new Object[]{
                    p.getId(),
                    p.getFornecedor(),
                    sdf.format(p.getData()),
                    p.getValorTotal(),
                    p.getStatus()
                });
            }
        }
    }
    
    public void listarPedidosConcluidos() {
        List<Pedidos> listaConcluido = pedidosDao.listarConcluidos();
        DefaultTableModel dadosConcluidos = (DefaultTableModel) tabelaConcluidos.getModel();
        dadosConcluidos.setNumRows(0);
        SimpleDateFormat sdf = new SimpleDateFormat("dd//MM//yyyy HH:mm");
        for (Pedidos p : listaConcluido) {
            if (p.getStatus().equals(Pedidos.Status.CONCLUIDO)) {
                dadosConcluidos.addRow(new Object[]{
                    p.getId(),
                    p.getFornecedor(),
                    sdf.format(p.getData()),
                    p.getValorTotal(),
                    p.getStatus()
                });
            }
        }
    }

    public boolean validaConclusaoPedido(JPanel painel, JRadioButton radBtnConcluido) {
        for (Component componente : painel.getComponents()) {
            if (componente instanceof JTextField txtField) {
                if (txtField.getText().trim().isEmpty()) {
                    return false;
                }
            }
        }
        return radBtnConcluido.isSelected();
    }

    public TelaFormularioPedidosFeitos(PedidosDAO pedidosDao, PecasPedidosDAO pecasPedidosDao, PecasDAO pecasDao) {
        initComponents();
        this.pedidosDao = pedidosDao;
        this.pecasPedidosDao = pecasPedidosDao;
        this.pecasDao = pecasDao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupStatus = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painelGuias = new javax.swing.JTabbedPane();
        pnlDadosPedido = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFornecedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        radBtnConcluido = new javax.swing.JRadioButton();
        radBtnPendente = new javax.swing.JRadioButton();
        txtDataEHora = new javax.swing.JTextField();
        pnlPedidosPendentes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPendentes = new javax.swing.JTable();
        lblFornecedorPendente = new javax.swing.JLabel();
        txtFornecedorPendente = new javax.swing.JTextField();
        btnPesquisarFornecedorPendente = new javax.swing.JButton();
        pnlPedidosConcluidos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaConcluidos = new javax.swing.JTable();
        txtFornecedorConcluido = new javax.swing.JTextField();
        lblFornecedorConcluido = new javax.swing.JLabel();
        btnPesquisarFornecedorConcluido = new javax.swing.JButton();
        btnConcluido = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário de Pedidos Realizados");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(809, 75));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulário de Pedidos Realizados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        painelGuias.setPreferredSize(new java.awt.Dimension(797, 100));

        jLabel2.setText("Id:");

        txtId.setEditable(false);
        txtId.setEnabled(false);

        jLabel3.setText("Fornecedor:");

        txtFornecedor.setEditable(false);
        txtFornecedor.setEnabled(false);

        jLabel4.setText("Data e Hora:");

        jLabel5.setText("Valor Total:");

        txtValorTotal.setEditable(false);
        txtValorTotal.setEnabled(false);

        btnGroupStatus.add(radBtnConcluido);
        radBtnConcluido.setText("Concluído");

        btnGroupStatus.add(radBtnPendente);
        radBtnPendente.setText("Pendente");

        txtDataEHora.setEditable(false);
        txtDataEHora.setEnabled(false);

        javax.swing.GroupLayout pnlDadosPedidoLayout = new javax.swing.GroupLayout(pnlDadosPedido);
        pnlDadosPedido.setLayout(pnlDadosPedidoLayout);
        pnlDadosPedidoLayout.setHorizontalGroup(
            pnlDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDadosPedidoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDadosPedidoLayout.createSequentialGroup()
                        .addGroup(pnlDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadosPedidoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDadosPedidoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                        .addGroup(pnlDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadosPedidoLayout.createSequentialGroup()
                                .addComponent(radBtnConcluido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radBtnPendente))
                            .addGroup(pnlDadosPedidoLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDataEHora, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)))
                .addGap(62, 62, 62))
        );
        pnlDadosPedidoLayout.setVerticalGroup(
            pnlDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtDataEHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(pnlDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radBtnConcluido)
                    .addComponent(radBtnPendente))
                .addGap(40, 40, 40)
                .addGroup(pnlDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        painelGuias.addTab("Dados do Pedido", pnlDadosPedido);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 402));

        tabelaPendentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FORNECEDOR", "DATA/HORA", "VALOR TOTAL", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPendentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPendentesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPendentes);

        lblFornecedorPendente.setText("Fornecedor:");

        btnPesquisarFornecedorPendente.setText("Pesquisar");
        btnPesquisarFornecedorPendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarFornecedorPendenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPedidosPendentesLayout = new javax.swing.GroupLayout(pnlPedidosPendentes);
        pnlPedidosPendentes.setLayout(pnlPedidosPendentesLayout);
        pnlPedidosPendentesLayout.setHorizontalGroup(
            pnlPedidosPendentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPedidosPendentesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPedidosPendentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
                    .addGroup(pnlPedidosPendentesLayout.createSequentialGroup()
                        .addComponent(lblFornecedorPendente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFornecedorPendente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisarFornecedorPendente)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlPedidosPendentesLayout.setVerticalGroup(
            pnlPedidosPendentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPedidosPendentesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlPedidosPendentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornecedorPendente)
                    .addComponent(txtFornecedorPendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarFornecedorPendente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painelGuias.addTab("Pedidos Pendentes", pnlPedidosPendentes);

        tabelaConcluidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FORNECEDOR", "DATA/HORA", "VALOR TOTAL", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaConcluidos);

        lblFornecedorConcluido.setText("Fornecedor:");

        btnPesquisarFornecedorConcluido.setText("Pesquisar");

        javax.swing.GroupLayout pnlPedidosConcluidosLayout = new javax.swing.GroupLayout(pnlPedidosConcluidos);
        pnlPedidosConcluidos.setLayout(pnlPedidosConcluidosLayout);
        pnlPedidosConcluidosLayout.setHorizontalGroup(
            pnlPedidosConcluidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPedidosConcluidosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPedidosConcluidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
                    .addGroup(pnlPedidosConcluidosLayout.createSequentialGroup()
                        .addComponent(lblFornecedorConcluido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFornecedorConcluido, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisarFornecedorConcluido)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlPedidosConcluidosLayout.setVerticalGroup(
            pnlPedidosConcluidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPedidosConcluidosLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(pnlPedidosConcluidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornecedorConcluido)
                    .addComponent(txtFornecedorConcluido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarFornecedorConcluido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painelGuias.addTab("Pedidos Concluídos", pnlPedidosConcluidos);

        btnConcluido.setText("Concluído");
        btnConcluido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluidoActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelGuias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(btnConcluido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpar)
                .addGap(220, 220, 220))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelGuias, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConcluido)
                    .addComponent(btnLimpar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listarPedidosPendentes();
        listarPedidosConcluidos();
    }//GEN-LAST:event_formWindowActivated

    private void btnPesquisarFornecedorPendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarFornecedorPendenteActionPerformed
        String nomeFornecedor = txtFornecedorPendente.getText() + "%";
        List<Pedidos> listaPedidosPendentes = pedidosDao.filtrarPedidosPendentesFornecedor(nomeFornecedor);
        DefaultTableModel dadosPedidosPendentes = (DefaultTableModel) tabelaPendentes.getModel();
        dadosPedidosPendentes.setRowCount(0);
        for (Pedidos pedidos : listaPedidosPendentes) {
            dadosPedidosPendentes.addRow(new Object[]{
                pedidos.getId(),
                pedidos.getFornecedor(),
                pedidos.getData(),
                pedidos.getStatus(),
                pedidos.getValorTotal()
            });
        }
    }//GEN-LAST:event_btnPesquisarFornecedorPendenteActionPerformed

    private void tabelaPendentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPendentesMouseClicked
        painelGuias.setSelectedIndex(0);
        txtId.setText(tabelaPendentes.getValueAt(tabelaPendentes.getSelectedRow(), 0).toString());
        txtFornecedor.setText(tabelaPendentes.getValueAt(tabelaPendentes.getSelectedRow(), 1).toString());
        txtDataEHora.setText(tabelaPendentes.getValueAt(tabelaPendentes.getSelectedRow(), 2).toString());
        txtValorTotal.setText(tabelaPendentes.getValueAt(tabelaPendentes.getSelectedRow(), 3).toString());
        radBtnPendente.setSelected(true);
    }//GEN-LAST:event_tabelaPendentesMouseClicked

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        btnGroupStatus.clearSelection();
        limpar.limparCampos(pnlDadosPedido);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnConcluidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluidoActionPerformed
        boolean podeConcluir = validaConclusaoPedido(pnlDadosPedido, radBtnConcluido);
        if (podeConcluir) {
            int id = Integer.parseInt(txtId.getText());
            boolean sucesso = pedidosDao.setConcluido(id, Pedidos.Status.CONCLUIDO);
            if (sucesso) {
                JOptionPane.showMessageDialog(this, "Status do pedido atualizado com sucesso.");

                List<PecasPedidos> itensPedido = pecasPedidosDao.buscarItensPorPedido(id);
                
                for (PecasPedidos item : itensPedido) {
                    int idPeca = item.getPeca().getId();
                    int qtdEstoque = pecasDao.retornaQuantidadeEstoque(idPeca);
                    int qtdComprada = item.getQuantidade();
                    int qtdAtualziada = qtdEstoque + qtdComprada;
                    
                    pecasDao.alterarEstoque(idPeca, qtdAtualziada);
                }

                btnGroupStatus.clearSelection();
                limpar.limparCampos(pnlDadosPedido);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Verifique se os campos estao preenchidos e selecione o botão Concluído");
        }
    }//GEN-LAST:event_btnConcluidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioPedidosFeitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioPedidosFeitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioPedidosFeitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioPedidosFeitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Connection conn = MySQLConnection.getConnection();
                    PedidosDAO pedidosDao = new PedidosDAO(conn);
                    PecasPedidosDAO pecasPedidosDao = new PecasPedidosDAO(conn);
                    PecasDAO pecasDao = new PecasDAO(conn);

                    new TelaFormularioPedidosFeitos(pedidosDao, pecasPedidosDao, pecasDao).setVisible(true);
                } catch (Exception e) {

                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConcluido;
    private javax.swing.ButtonGroup btnGroupStatus;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisarFornecedorConcluido;
    private javax.swing.JButton btnPesquisarFornecedorPendente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFornecedorConcluido;
    private javax.swing.JLabel lblFornecedorPendente;
    private javax.swing.JTabbedPane painelGuias;
    private javax.swing.JPanel pnlDadosPedido;
    private javax.swing.JPanel pnlPedidosConcluidos;
    private javax.swing.JPanel pnlPedidosPendentes;
    private javax.swing.JRadioButton radBtnConcluido;
    private javax.swing.JRadioButton radBtnPendente;
    private javax.swing.JTable tabelaConcluidos;
    private javax.swing.JTable tabelaPendentes;
    private javax.swing.JTextField txtDataEHora;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtFornecedorConcluido;
    private javax.swing.JTextField txtFornecedorPendente;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
