package gui;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import javax.swing.*;
import jdbc.MySQLConnection;

public final class TelaAreaDeTrabalho extends javax.swing.JFrame {

    private final Connection conn;

    public void janelaCliente() {
        TelaFormularioClientes tfc = new TelaFormularioClientes(conn);
        tfc.setVisible(true);
    }
    
    public void janelaFornecedor() {
        TelaFormularioFornecedores tff = new TelaFormularioFornecedores(conn);
        tff.setVisible(true);
    }
    
    public void janelaFuncionario() {
        TelaFormularioFuncionarios tff = new TelaFormularioFuncionarios(conn);
        tff.setVisible(true);
    }
    
    public void janelaPecas() {
        TelaFormularioPecas tfp = new TelaFormularioPecas(conn);
        tfp.setVisible(true);
    }
    
    public void janelaPedido() {
        TelaFormularioPedidos tfpd = new TelaFormularioPedidos(conn);
        tfpd.setVisible(true);
    }

    public void aplicarHoverTranslucido(JButton botao, Color hoverColor, Color defaultColor) {
        botao.setOpaque(true);
        botao.setBackground(defaultColor);
        botao.setBorderPainted(false);
        botao.setFocusPainted(false);
        botao.setContentAreaFilled(true);

        botao.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao.setBackground(hoverColor);
                botao.repaint();
                botao.getParent().revalidate();
                botao.getParent().repaint();
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao.setBackground(defaultColor);
                botao.repaint();
                botao.getParent().revalidate();
                botao.getParent().repaint();
            }
        });
    }

    /**
     * Creates new form TelaAreaDeTrabalho
     */
    public TelaAreaDeTrabalho(Connection conn) {
        initComponents();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.conn = conn;
        aplicarHoverTranslucido(btnCliente, new Color(0, 120, 215, 80), new Color(0, 0, 0, 0));
        aplicarHoverTranslucido(btnFornecedor, new Color(0, 120, 215, 80), new Color(0, 0, 0, 0));
        aplicarHoverTranslucido(btnFuncionario, new Color(0, 120, 215, 80), new Color(0, 0, 0, 0));
        aplicarHoverTranslucido(btnPecas, new Color(0, 120, 215, 80), new Color(0, 0, 0, 0));
        aplicarHoverTranslucido(btnPedido, new Color(0, 120, 215, 80), new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/imgFundo/mecanica.jpg"));
        Image image = icon.getImage();
        painelDesktop = new javax.swing.JDesktopPane() {
            public void paintComponent(Graphics g) {
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }
        };
        btnCliente = new javax.swing.JButton();
        btnFuncionario = new javax.swing.JButton();
        btnFornecedor = new javax.swing.JButton();
        btnPecas = new javax.swing.JButton();
        btnPedido = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemFormClientes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemFormFuncionarios = new javax.swing.JMenuItem();
        menuItemFormCargos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuItemFormFornecedores = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        menuItemFormEstoque = new javax.swing.JMenuItem();
        menuItemFormPecas2 = new javax.swing.JMenuItem();
        menuItemFormPecas = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuItemFormPedidos = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuItemFormOrdemServico = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuItemTrocarUsuario = new javax.swing.JMenuItem();
        menuItemSairSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Area de Trabalho");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        painelDesktop.setBackground(new java.awt.Color(242, 242, 242));

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clientes.png"))); // NOI18N
        btnCliente.setText("Clientes");
        btnCliente.setHorizontalTextPosition(SwingConstants.CENTER);
        btnCliente.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnCliente.setBorderPainted(false);
        btnCliente.setContentAreaFilled(false);
        btnCliente.setFocusPainted(true);
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        btnFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/funcionarios.png"))); // NOI18N
        btnFuncionario.setText("Funcionários");
        btnFuncionario.setHorizontalTextPosition(SwingConstants.CENTER);
        btnFuncionario.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnFuncionario.setBorderPainted(false);
        btnFuncionario.setContentAreaFilled(false);
        btnFuncionario.setFocusPainted(false);
        btnFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionarioActionPerformed(evt);
            }
        });

        btnFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fornecedores.png"))); // NOI18N
        btnFornecedor.setText("Fornecedores");
        btnFornecedor.setHorizontalTextPosition(SwingConstants.CENTER);
        btnFornecedor.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnFornecedor.setBorderPainted(false);
        btnFornecedor.setContentAreaFilled(false);
        btnFornecedor.setFocusPainted(false);
        btnFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorActionPerformed(evt);
            }
        });

        btnPecas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pecas.png"))); // NOI18N
        btnPecas.setText("Peças");
        btnPecas.setHorizontalTextPosition(SwingConstants.CENTER);
        btnPecas.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnPecas.setBorderPainted(false);
        btnPecas.setContentAreaFilled(false);
        btnPecas.setFocusPainted(false);
        btnPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPecasActionPerformed(evt);
            }
        });

        btnPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pedido.png"))); // NOI18N
        btnPedido.setText("Pedido");
        btnPedido.setHorizontalTextPosition(SwingConstants.CENTER);
        btnPedido.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnPedido.setBorderPainted(false);
        btnPedido.setContentAreaFilled(false);
        btnPedido.setFocusPainted(false);
        btnPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoActionPerformed(evt);
            }
        });

        painelDesktop.setLayer(btnCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDesktop.setLayer(btnFuncionario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDesktop.setLayer(btnFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDesktop.setLayer(btnPecas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDesktop.setLayer(btnPedido, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelDesktopLayout = new javax.swing.GroupLayout(painelDesktop);
        painelDesktop.setLayout(painelDesktopLayout);
        painelDesktopLayout.setHorizontalGroup(
            painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDesktopLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(250, 250, 250)
                .addGroup(painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(250, 250, 250)
                .addComponent(btnPecas)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        painelDesktopLayout.setVerticalGroup(
            painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDesktopLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCliente)
                    .addComponent(btnFornecedor)
                    .addComponent(btnPecas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(150, 150, 150)
                .addGroup(painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFuncionario)
                    .addComponent(btnPedido))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jMenu1.setText("Clientes");

        menuItemFormClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemFormClientes.setText("Formulário de Clientes");
        menuItemFormClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFormClientesActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemFormClientes);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Funcionários");

        menuItemFormFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemFormFuncionarios.setText("Formulário de Funcionários");
        menuItemFormFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFormFuncionariosActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemFormFuncionarios);

        menuItemFormCargos.setText("Formulário de Cargos");
        menuItemFormCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFormCargosActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemFormCargos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Fornecedores");

        menuItemFormFornecedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemFormFornecedores.setText("Formulário de Fornecedores");
        menuItemFormFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFormFornecedoresActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemFormFornecedores);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Peças");

        jMenu8.setText("Minhas Peças");

        menuItemFormEstoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemFormEstoque.setText("Controle de Estoque");
        menuItemFormEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFormEstoqueActionPerformed(evt);
            }
        });
        jMenu8.add(menuItemFormEstoque);

        menuItemFormPecas2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemFormPecas2.setText("Consulta de Peças");
        menuItemFormPecas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFormPecas2ActionPerformed(evt);
            }
        });
        jMenu8.add(menuItemFormPecas2);

        menuItemFormPecas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemFormPecas.setText("Formulário de Peças");
        menuItemFormPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFormPecasActionPerformed(evt);
            }
        });
        jMenu8.add(menuItemFormPecas);

        jMenu4.add(jMenu8);

        jMenuBar1.add(jMenu4);

        jMenu7.setText("Pedidos");

        menuItemFormPedidos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemFormPedidos.setText("Formulário de Pedidos");
        menuItemFormPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFormPedidosActionPerformed(evt);
            }
        });
        jMenu7.add(menuItemFormPedidos);

        jMenuBar1.add(jMenu7);

        jMenu5.setText("Ordem de Serviço");

        menuItemFormOrdemServico.setText("Formulário de OS");
        jMenu5.add(menuItemFormOrdemServico);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Sair");

        menuItemTrocarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemTrocarUsuario.setText("Trocar de Usuário");
        menuItemTrocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTrocarUsuarioActionPerformed(evt);
            }
        });
        jMenu6.add(menuItemTrocarUsuario);

        menuItemSairSistema.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemSairSistema.setText("Sair do Sistema");
        menuItemSairSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairSistemaActionPerformed(evt);
            }
        });
        jMenu6.add(menuItemSairSistema);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDesktop)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemFormClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFormClientesActionPerformed
        // abre o formulário de clientes na tela
        janelaCliente();
    }//GEN-LAST:event_menuItemFormClientesActionPerformed

    private void menuItemFormFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFormFuncionariosActionPerformed
        // abre o formulário de funcionários na tela
        janelaFuncionario();
    }//GEN-LAST:event_menuItemFormFuncionariosActionPerformed

    private void menuItemFormFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFormFornecedoresActionPerformed
        // abre o formulário de fornecedores na tela
        janelaFornecedor();
    }//GEN-LAST:event_menuItemFormFornecedoresActionPerformed

    private void menuItemFormCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFormCargosActionPerformed
        // abre o formulário de cargos na tela
        TelaFormularioCargos tfc = new TelaFormularioCargos(conn);
        tfc.setVisible(true);
    }//GEN-LAST:event_menuItemFormCargosActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // maximiza a janela
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowActivated

    private void menuItemTrocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTrocarUsuarioActionPerformed
        // solicita confirmação para trocar de usuário        
        int opcao = JOptionPane.showConfirmDialog(null,
                "Você deseja trocar de usuário?", "Aviso",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (opcao == JOptionPane.YES_OPTION) {
            TelaLogin tl = new TelaLogin(conn);
            this.dispose();
            tl.setVisible(true);
        }
    }//GEN-LAST:event_menuItemTrocarUsuarioActionPerformed

    private void menuItemSairSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairSistemaActionPerformed
        // solicita confirmação para sair do sistema
        int opcao = JOptionPane.showConfirmDialog(null,
                "Sair do sistema?", "Aviso",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (opcao == JOptionPane.YES_OPTION) {
            this.dispose();
            MySQLConnection.closeConnection();
        }
    }//GEN-LAST:event_menuItemSairSistemaActionPerformed

    private void menuItemFormPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFormPecasActionPerformed
        // abre o formulário de Peças na tela
        janelaPecas();
    }//GEN-LAST:event_menuItemFormPecasActionPerformed

    private void menuItemFormPecas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFormPecas2ActionPerformed
        // abre o formulário de Peças na tela, na aba de consulta de Peças
        TelaFormularioPecas tfpConsulta = new TelaFormularioPecas(conn);
        tfpConsulta.painelGuias.setSelectedIndex(1);
        tfpConsulta.setVisible(true);
    }//GEN-LAST:event_menuItemFormPecas2ActionPerformed

    private void menuItemFormEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFormEstoqueActionPerformed
        // abre o formulário de estoque na tela
        TelaFormularioEstoque tle = new TelaFormularioEstoque(conn);
        tle.setVisible(true);
    }//GEN-LAST:event_menuItemFormEstoqueActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int opcao = JOptionPane.showConfirmDialog(null,
                "Ao fechar a área de trabalho você será desconectado."
                + " Tem certeza que quer sair?", "Aviso",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (opcao == JOptionPane.YES_OPTION) {
            this.dispose();
            MySQLConnection.closeConnection();
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        janelaCliente();
    }//GEN-LAST:event_btnClienteActionPerformed

    private void menuItemFormPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFormPedidosActionPerformed
        janelaPedido();
    }//GEN-LAST:event_menuItemFormPedidosActionPerformed

    private void btnFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionarioActionPerformed
        janelaFuncionario();
    }//GEN-LAST:event_btnFuncionarioActionPerformed

    private void btnFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorActionPerformed
        janelaFornecedor();
    }//GEN-LAST:event_btnFornecedorActionPerformed

    private void btnPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoActionPerformed
        janelaPedido();
    }//GEN-LAST:event_btnPedidoActionPerformed

    private void btnPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPecasActionPerformed
        janelaPecas();
    }//GEN-LAST:event_btnPecasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAreaDeTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                Connection conn = MySQLConnection.getConnection();
                new TelaAreaDeTrabalho(conn).setVisible(true);
            } catch (Exception e) {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnFornecedor;
    private javax.swing.JButton btnFuncionario;
    private javax.swing.JButton btnPecas;
    private javax.swing.JButton btnPedido;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuItemFormCargos;
    private javax.swing.JMenuItem menuItemFormClientes;
    private javax.swing.JMenuItem menuItemFormEstoque;
    private javax.swing.JMenuItem menuItemFormFornecedores;
    private javax.swing.JMenuItem menuItemFormFuncionarios;
    private javax.swing.JMenuItem menuItemFormOrdemServico;
    private javax.swing.JMenuItem menuItemFormPecas;
    private javax.swing.JMenuItem menuItemFormPecas2;
    private javax.swing.JMenuItem menuItemFormPedidos;
    private javax.swing.JMenuItem menuItemSairSistema;
    private javax.swing.JMenuItem menuItemTrocarUsuario;
    private javax.swing.JDesktopPane painelDesktop;
    // End of variables declaration//GEN-END:variables
}
