package gui;

import dao.FornecedoresDAO;
import dao.PecasDAO;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Fornecedores;
import model.Pecas;
import utilidades.Utilidades;

public class TelaFormularioPedidos extends javax.swing.JFrame {

    private final Utilidades util = new Utilidades();
    private final SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    Date dataAtual = new Date();
    String dataFormatada = sdf.format(dataAtual);
    double subtotal, total;
    int idFornecedor, idFornecedorCarrinho;
    DefaultTableModel meuPedido;

    public void filtrar() {
        String cnpj = txtCnpj.getText();
        PecasDAO pecasDao = new PecasDAO();
        List<Pecas> lista = pecasDao.filtrarPecasFornecedor(cnpj);
        DefaultTableModel dados = (DefaultTableModel) tabelaPecasFornecedor.getModel();
        dados.setNumRows(0);
        for (Pecas p : lista) {
            dados.addRow(new Object[]{
                p.getId(),
                p.getFornecedores(),
                p.getNome(),
                p.getDescricao(),
                p.getQuantidade(),
                p.getValorUnidadeFornecedor(),
                p.getValorUnidadeCliente()

            });
        }
    }

    private void calcularValorTotalPeca() {
        try {
            double valorFornecedor = Double.parseDouble(txtPrecoUnidadeFornecedor.getText());
            int qtdPedido = Integer.parseInt(txtQtdPedido.getText());
            double valorTotalPeca = valorFornecedor * qtdPedido;
            txtValorTotalPeca.setText(String.valueOf(valorTotalPeca));
        } catch (NumberFormatException e) {
            txtValorTotalPeca.setText("0.0");
        }
    }

    public void listarPecasFornecedor() {

    }

    public TelaFormularioPedidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelDadosFornecedor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDataAtual = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNomeFornecedor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmailFornecedor = new javax.swing.JTextField();
        btnPesquisarCnpj = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaPecasFornecedor = new javax.swing.JTable();
        btnLimparCnpj = new javax.swing.JButton();
        panelDadosPeca = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtIdPeca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNomePeca = new javax.swing.JTextField();
        txtQtdEstoque = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtQtdPedido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPrecoUnidadeFornecedor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtValorTotalPeca = new javax.swing.JTextField();
        btnAdicionarPeca = new javax.swing.JButton();
        btnLimparPeca = new javax.swing.JButton();
        panelPedido = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPecasPedido = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        txtTotalPedido = new javax.swing.JTextField();
        btnFazerPedido = new javax.swing.JButton();
        btnCancelarPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário de Pedidos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulário de Pedidos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        PanelDadosFornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Fornecedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel2.setText("CNPJ:");

        try {
            txtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("Data:");

        txtDataAtual.setEditable(false);
        try {
            txtDataAtual.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter(" ##/##/#### ")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Nome:");

        txtNomeFornecedor.setEditable(false);
        txtNomeFornecedor.setEnabled(false);

        jLabel5.setText("E-mail:");

        txtEmailFornecedor.setEditable(false);
        txtEmailFornecedor.setEnabled(false);

        btnPesquisarCnpj.setText("Pesquisar");
        btnPesquisarCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarCnpjActionPerformed(evt);
            }
        });

        tabelaPecasFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FORNECEDOR", "NOME", "DESCRIÇÃO", "QUANTIDADE", "VALOR FORNECEDOR", "VALOR CLIENTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPecasFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPecasFornecedorMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaPecasFornecedor);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLimparCnpj.setText("Limpar");
        btnLimparCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCnpjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDadosFornecedorLayout = new javax.swing.GroupLayout(PanelDadosFornecedor);
        PanelDadosFornecedor.setLayout(PanelDadosFornecedorLayout);
        PanelDadosFornecedorLayout.setHorizontalGroup(
            PanelDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDadosFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelDadosFornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelDadosFornecedorLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnPesquisarCnpj))
                            .addComponent(txtNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDadosFornecedorLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEmailFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                                .addGap(97, 97, 97))
                            .addGroup(PanelDadosFornecedorLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnLimparCnpj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDataAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)))))
                .addContainerGap())
        );
        PanelDadosFornecedorLayout.setVerticalGroup(
            PanelDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDadosFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesquisarCnpj)
                        .addComponent(btnLimparCnpj))
                    .addGroup(PanelDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtDataAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PanelDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtEmailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDadosPeca.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da Peça", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel6.setText("Id:");

        txtIdPeca.setEditable(false);

        jLabel7.setText("Nome:");

        jLabel8.setText("Quantidade Estoque:");

        txtNomePeca.setEditable(false);

        txtQtdEstoque.setEditable(false);

        jLabel9.setText("Quantidade Pedido:");

        txtQtdPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c)) {
                    e.consume();
                }
                if (txtQtdPedido.getText().length() >= 6) {
                    e.consume();
                }
            }
        });
        txtQtdPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtdPedidoKeyReleased(evt);
            }
        });

        jLabel10.setText("Preço Unidade:");

        txtPrecoUnidadeFornecedor.setEditable(false);

        jLabel11.setText("Valor Total:");

        txtValorTotalPeca.setEditable(false);

        btnAdicionarPeca.setText("Adicionar");
        btnAdicionarPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarPecaActionPerformed(evt);
            }
        });

        btnLimparPeca.setText("Limpar");
        btnLimparPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparPecaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDadosPecaLayout = new javax.swing.GroupLayout(panelDadosPeca);
        panelDadosPeca.setLayout(panelDadosPecaLayout);
        panelDadosPecaLayout.setHorizontalGroup(
            panelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosPecaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDadosPecaLayout.createSequentialGroup()
                        .addGroup(panelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelDadosPecaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtQtdEstoque))
                            .addGroup(panelDadosPecaLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtQtdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDadosPecaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValorTotalPeca))
                            .addGroup(panelDadosPecaLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrecoUnidadeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panelDadosPecaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomePeca, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelDadosPecaLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnAdicionarPeca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimparPeca)
                .addGap(70, 70, 70))
        );
        panelDadosPecaLayout.setVerticalGroup(
            panelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosPecaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtIdPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtNomePeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtQtdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtPrecoUnidadeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtQtdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtValorTotalPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(panelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarPeca)
                    .addComponent(btnLimparPeca))
                .addGap(32, 32, 32))
        );

        panelPedido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Peças Pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tabelaPecasPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PEÇA", "QUANTIDADE", "PREÇO", "SUBTOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaPecasPedido);

        jLabel12.setText("Total do Pedido:");

        txtTotalPedido.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        btnFazerPedido.setText("Fazer Pedido");

        btnCancelarPedido.setText("Cancelar Pedido");

        javax.swing.GroupLayout panelPedidoLayout = new javax.swing.GroupLayout(panelPedido);
        panelPedido.setLayout(panelPedidoLayout);
        panelPedidoLayout.setHorizontalGroup(
            panelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panelPedidoLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCancelarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFazerPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPedidoLayout.setVerticalGroup(
            panelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPedidoLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPedidoLayout.createSequentialGroup()
                        .addComponent(btnFazerPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(btnCancelarPedido))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTotalPedido, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelDadosFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelDadosPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDadosFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDadosPeca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarCnpjActionPerformed
        String cnpj = txtCnpj.getText();
        FornecedoresDAO fornecedoresDao = new FornecedoresDAO();
        Fornecedores fornecedor = fornecedoresDao.buscarFornecedor(cnpj);

        if (fornecedor.getCnpj() != null) {
            txtNomeFornecedor.setText(fornecedor.getNome());
            txtEmailFornecedor.setText(fornecedor.getEmail());
            txtCnpj.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Fornecedor não encontrado para o CNPJ fornecido!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        filtrar();
    }//GEN-LAST:event_btnPesquisarCnpjActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        filtrar();
        txtDataAtual.setText(dataFormatada);

    }//GEN-LAST:event_formWindowActivated

    private void tabelaPecasFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPecasFornecedorMouseClicked
        txtIdPeca.setText(tabelaPecasFornecedor.getValueAt(tabelaPecasFornecedor.getSelectedRow(), 0).toString());
        txtNomePeca.setText(tabelaPecasFornecedor.getValueAt(tabelaPecasFornecedor.getSelectedRow(), 2).toString());
        txtQtdEstoque.setText(tabelaPecasFornecedor.getValueAt(tabelaPecasFornecedor.getSelectedRow(), 4).toString());
        txtPrecoUnidadeFornecedor.setText(tabelaPecasFornecedor.getValueAt(tabelaPecasFornecedor.getSelectedRow(), 5).toString());
        txtValorTotalPeca.setText("0.0");
    }//GEN-LAST:event_tabelaPecasFornecedorMouseClicked

    private void btnLimparPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparPecaActionPerformed
        util.limparCampos(panelDadosPeca);
    }//GEN-LAST:event_btnLimparPecaActionPerformed

    private void btnLimparCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCnpjActionPerformed
        util.limparCampos(PanelDadosFornecedor);
        util.limparCampos(panelDadosPeca);
        txtDataAtual.setText(dataFormatada);
        txtCnpj.setEnabled(true);
        txtCnpj.requestFocus();

    }//GEN-LAST:event_btnLimparCnpjActionPerformed

    private void btnAdicionarPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarPecaActionPerformed
        String nome = txtNomePeca.getText();
        PecasDAO pecasDao = new PecasDAO();
        Pecas peca = pecasDao.buscarPeca(nome);

        if (peca != null) {
            idFornecedor = peca.getFornecedores().getId();
            int idFornecedorPeca = peca.getFornecedores().getId();            
            subtotal = Double.parseDouble(txtValorTotalPeca.getText());
            total += subtotal;

            if (idFornecedorCarrinho == 0) {
                idFornecedorCarrinho = idFornecedor;
            }
            if (idFornecedorPeca == idFornecedorCarrinho) {
                txtTotalPedido.setText(String.valueOf(total));
                meuPedido = (DefaultTableModel) tabelaPecasPedido.getModel();
                meuPedido.addRow(new Object[]{
                    txtIdPeca.getText(),
                    txtNomePeca.getText(),
                    txtQtdPedido.getText(),
                    txtPrecoUnidadeFornecedor.getText(),
                    subtotal
                });
            } else {
                JOptionPane.showMessageDialog(null, "A peça não pode ser adicionada ao carrinho pois o fornecedor é diferente das outras!", "Atenção", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não foi possível adicionar ao carrinho.\n Faltam informações.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        util.limparCampos(panelDadosPeca);

    }//GEN-LAST:event_btnAdicionarPecaActionPerformed

    private void txtQtdPedidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdPedidoKeyReleased
        calcularValorTotalPeca();
    }//GEN-LAST:event_txtQtdPedidoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFormularioPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDadosFornecedor;
    private javax.swing.JButton btnAdicionarPeca;
    private javax.swing.JButton btnCancelarPedido;
    private javax.swing.JButton btnFazerPedido;
    private javax.swing.JButton btnLimparCnpj;
    private javax.swing.JButton btnLimparPeca;
    private javax.swing.JButton btnPesquisarCnpj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelDadosPeca;
    private javax.swing.JPanel panelPedido;
    private javax.swing.JTable tabelaPecasFornecedor;
    private javax.swing.JTable tabelaPecasPedido;
    private javax.swing.JFormattedTextField txtCnpj;
    private javax.swing.JFormattedTextField txtDataAtual;
    private javax.swing.JTextField txtEmailFornecedor;
    private javax.swing.JTextField txtIdPeca;
    private javax.swing.JTextField txtNomeFornecedor;
    private javax.swing.JTextField txtNomePeca;
    private javax.swing.JTextField txtPrecoUnidadeFornecedor;
    private javax.swing.JTextField txtQtdEstoque;
    private javax.swing.JTextField txtQtdPedido;
    private javax.swing.JTextField txtTotalPedido;
    private javax.swing.JTextField txtValorTotalPeca;
    // End of variables declaration//GEN-END:variables

}
